// <auto-generated />
using System;
using KnihovnaHer.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnihovnaHer.Data.Migrations
{
    [DbContext(typeof(KnihovnaHerDbContext))]
    [Migration("20250531172837_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HraZanr", b =>
                {
                    b.Property<long>("HryHraId")
                        .HasColumnType("bigint");

                    b.Property<long>("ZanryZanrId")
                        .HasColumnType("bigint");

                    b.HasKey("HryHraId", "ZanryZanrId");

                    b.HasIndex("ZanryZanrId");

                    b.ToTable("HraZanr");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Hra", b =>
                {
                    b.Property<long>("HraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HraId"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokVydani")
                        .HasColumnType("int");

                    b.Property<long?>("VydavatelId")
                        .HasColumnType("bigint");

                    b.HasKey("HraId");

                    b.HasIndex("VydavatelId");

                    b.ToTable("Hry");

                    b.HasData(
                        new
                        {
                            HraId = 1L,
                            Nazev = "Elden Ring",
                            RokVydani = 2022,
                            VydavatelId = 2L
                        },
                        new
                        {
                            HraId = 2L,
                            Nazev = "Starfield",
                            RokVydani = 2023,
                            VydavatelId = 3L
                        },
                        new
                        {
                            HraId = 3L,
                            Nazev = "Baldur's Gate 3",
                            RokVydani = 2023,
                            VydavatelId = 10L
                        },
                        new
                        {
                            HraId = 4L,
                            Nazev = "Helldivers 2",
                            RokVydani = 2024,
                            VydavatelId = 20L
                        },
                        new
                        {
                            HraId = 5L,
                            Nazev = "Palworld",
                            RokVydani = 2024,
                            VydavatelId = 15L
                        },
                        new
                        {
                            HraId = 6L,
                            Nazev = "GTA V",
                            RokVydani = 2013,
                            VydavatelId = 19L
                        },
                        new
                        {
                            HraId = 7L,
                            Nazev = "Cyberpunk 2077",
                            RokVydani = 2020,
                            VydavatelId = 5L
                        },
                        new
                        {
                            HraId = 8L,
                            Nazev = "Hogwarts Legacy",
                            RokVydani = 2023,
                            VydavatelId = 27L
                        },
                        new
                        {
                            HraId = 9L,
                            Nazev = "Assassin’s Creed Mirage",
                            RokVydani = 2023,
                            VydavatelId = 25L
                        },
                        new
                        {
                            HraId = 10L,
                            Nazev = "Call of Duty: Modern Warfare II",
                            RokVydani = 2022,
                            VydavatelId = 1L
                        },
                        new
                        {
                            HraId = 11L,
                            Nazev = "The Sims 4",
                            RokVydani = 2014,
                            VydavatelId = 8L
                        },
                        new
                        {
                            HraId = 12L,
                            Nazev = "Resident Evil 4 Remake",
                            RokVydani = 2023,
                            VydavatelId = 6L
                        },
                        new
                        {
                            HraId = 13L,
                            Nazev = "Stardew Valley",
                            RokVydani = 2016,
                            VydavatelId = 7L
                        },
                        new
                        {
                            HraId = 14L,
                            Nazev = "Dead Space Remake",
                            RokVydani = 2023,
                            VydavatelId = 8L
                        },
                        new
                        {
                            HraId = 15L,
                            Nazev = "Cities: Skylines II",
                            RokVydani = 2023,
                            VydavatelId = 14L
                        },
                        new
                        {
                            HraId = 16L,
                            Nazev = "ARK: Survival Ascended",
                            RokVydani = 2023,
                            VydavatelId = 22L
                        },
                        new
                        {
                            HraId = 17L,
                            Nazev = "Hades II",
                            RokVydani = 2024,
                            VydavatelId = 23L
                        },
                        new
                        {
                            HraId = 18L,
                            Nazev = "The Witcher 3",
                            RokVydani = 2015,
                            VydavatelId = 5L
                        },
                        new
                        {
                            HraId = 19L,
                            Nazev = "Fortnite",
                            RokVydani = 2017,
                            VydavatelId = 9L
                        },
                        new
                        {
                            HraId = 20L,
                            Nazev = "Battlefield V",
                            RokVydani = 2018,
                            VydavatelId = 8L
                        },
                        new
                        {
                            HraId = 21L,
                            Nazev = "Red Dead Redemption 2",
                            RokVydani = 2018,
                            VydavatelId = 19L
                        },
                        new
                        {
                            HraId = 22L,
                            Nazev = "Overwatch 2",
                            RokVydani = 2022,
                            VydavatelId = 4L
                        },
                        new
                        {
                            HraId = 23L,
                            Nazev = "Minecraft",
                            RokVydani = 2011,
                            VydavatelId = 12L
                        },
                        new
                        {
                            HraId = 24L,
                            Nazev = "Valorant",
                            RokVydani = 2020,
                            VydavatelId = 18L
                        },
                        new
                        {
                            HraId = 25L,
                            Nazev = "League of Legends",
                            RokVydani = 2009,
                            VydavatelId = 18L
                        },
                        new
                        {
                            HraId = 26L,
                            Nazev = "Dota 2",
                            RokVydani = 2013,
                            VydavatelId = 26L
                        },
                        new
                        {
                            HraId = 27L,
                            Nazev = "Apex Legends",
                            RokVydani = 2019,
                            VydavatelId = 8L
                        },
                        new
                        {
                            HraId = 28L,
                            Nazev = "Sea of Thieves",
                            RokVydani = 2018,
                            VydavatelId = 16L
                        },
                        new
                        {
                            HraId = 29L,
                            Nazev = "The Legend of Zelda: TOTK",
                            RokVydani = 2023,
                            VydavatelId = 13L
                        },
                        new
                        {
                            HraId = 30L,
                            Nazev = "Super Mario Odyssey",
                            RokVydani = 2017,
                            VydavatelId = 13L
                        },
                        new
                        {
                            HraId = 31L,
                            Nazev = "Hollow Knight: Silksong",
                            RokVydani = 2025,
                            VydavatelId = 24L
                        },
                        new
                        {
                            HraId = 32L,
                            Nazev = "Diablo IV",
                            RokVydani = 2023,
                            VydavatelId = 4L
                        },
                        new
                        {
                            HraId = 33L,
                            Nazev = "Final Fantasy XVI",
                            RokVydani = 2023,
                            VydavatelId = 21L
                        },
                        new
                        {
                            HraId = 34L,
                            Nazev = "Ghost of Tsushima",
                            RokVydani = 2020,
                            VydavatelId = 20L
                        },
                        new
                        {
                            HraId = 35L,
                            Nazev = "Death Stranding",
                            RokVydani = 2019,
                            VydavatelId = 20L
                        },
                        new
                        {
                            HraId = 36L,
                            Nazev = "The Last of Us Part I",
                            RokVydani = 2022,
                            VydavatelId = 20L
                        },
                        new
                        {
                            HraId = 37L,
                            Nazev = "Returnal",
                            RokVydani = 2021,
                            VydavatelId = 20L
                        },
                        new
                        {
                            HraId = 38L,
                            Nazev = "Forza Horizon 5",
                            RokVydani = 2021,
                            VydavatelId = 11L
                        },
                        new
                        {
                            HraId = 39L,
                            Nazev = "Microsoft Flight Simulator",
                            RokVydani = 2020,
                            VydavatelId = 11L
                        },
                        new
                        {
                            HraId = 40L,
                            Nazev = "Terraria",
                            RokVydani = 2011,
                            VydavatelId = 17L
                        });
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.StatusHry", b =>
                {
                    b.Property<long>("StatusHryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatusHryId"));

                    b.Property<DateTime?>("DatumDokonceni")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZacatku")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Hodnoceni")
                        .HasColumnType("int");

                    b.Property<long>("HraId")
                        .HasColumnType("bigint");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<string>("UzivatelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StatusHryId");

                    b.HasIndex("HraId");

                    b.HasIndex("UzivatelId");

                    b.ToTable("StatusHer");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Uzivatel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Vydavatel", b =>
                {
                    b.Property<long>("VydavatelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VydavatelId"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VydavatelId");

                    b.ToTable("Vydavatele");

                    b.HasData(
                        new
                        {
                            VydavatelId = 1L,
                            Nazev = "Activision"
                        },
                        new
                        {
                            VydavatelId = 2L,
                            Nazev = "Bandai Namco"
                        },
                        new
                        {
                            VydavatelId = 3L,
                            Nazev = "Bethesda"
                        },
                        new
                        {
                            VydavatelId = 4L,
                            Nazev = "Blizzard Entertainment"
                        },
                        new
                        {
                            VydavatelId = 5L,
                            Nazev = "CD Projekt"
                        },
                        new
                        {
                            VydavatelId = 6L,
                            Nazev = "Capcom"
                        },
                        new
                        {
                            VydavatelId = 7L,
                            Nazev = "ConcernedApe"
                        },
                        new
                        {
                            VydavatelId = 8L,
                            Nazev = "Electronic Arts"
                        },
                        new
                        {
                            VydavatelId = 9L,
                            Nazev = "Epic Games"
                        },
                        new
                        {
                            VydavatelId = 10L,
                            Nazev = "Larian Studios"
                        },
                        new
                        {
                            VydavatelId = 11L,
                            Nazev = "Microsoft"
                        },
                        new
                        {
                            VydavatelId = 12L,
                            Nazev = "Mojang"
                        },
                        new
                        {
                            VydavatelId = 13L,
                            Nazev = "Nintendo"
                        },
                        new
                        {
                            VydavatelId = 14L,
                            Nazev = "Paradox Interactive"
                        },
                        new
                        {
                            VydavatelId = 15L,
                            Nazev = "Pocketpair"
                        },
                        new
                        {
                            VydavatelId = 16L,
                            Nazev = "Rare"
                        },
                        new
                        {
                            VydavatelId = 17L,
                            Nazev = "Re-Logic"
                        },
                        new
                        {
                            VydavatelId = 18L,
                            Nazev = "Riot Games"
                        },
                        new
                        {
                            VydavatelId = 19L,
                            Nazev = "Rockstar Games"
                        },
                        new
                        {
                            VydavatelId = 20L,
                            Nazev = "Sony"
                        },
                        new
                        {
                            VydavatelId = 21L,
                            Nazev = "Square Enix"
                        },
                        new
                        {
                            VydavatelId = 22L,
                            Nazev = "Studio Wildcard"
                        },
                        new
                        {
                            VydavatelId = 23L,
                            Nazev = "Supergiant Games"
                        },
                        new
                        {
                            VydavatelId = 24L,
                            Nazev = "Team Cherry"
                        },
                        new
                        {
                            VydavatelId = 25L,
                            Nazev = "Ubisoft"
                        },
                        new
                        {
                            VydavatelId = 26L,
                            Nazev = "Valve"
                        },
                        new
                        {
                            VydavatelId = 27L,
                            Nazev = "Warner Bros."
                        });
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Zanr", b =>
                {
                    b.Property<long>("ZanrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ZanrId"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ZanrId");

                    b.HasIndex("Nazev");

                    b.ToTable("Zanry");

                    b.HasData(
                        new
                        {
                            ZanrId = 1L,
                            Nazev = "Action"
                        },
                        new
                        {
                            ZanrId = 2L,
                            Nazev = "Adventure"
                        },
                        new
                        {
                            ZanrId = 3L,
                            Nazev = "RPG"
                        },
                        new
                        {
                            ZanrId = 4L,
                            Nazev = "Sci-Fi"
                        },
                        new
                        {
                            ZanrId = 5L,
                            Nazev = "Strategy"
                        },
                        new
                        {
                            ZanrId = 6L,
                            Nazev = "Fantasy"
                        },
                        new
                        {
                            ZanrId = 7L,
                            Nazev = "Shooter"
                        },
                        new
                        {
                            ZanrId = 8L,
                            Nazev = "Survival"
                        },
                        new
                        {
                            ZanrId = 9L,
                            Nazev = "Simulation"
                        },
                        new
                        {
                            ZanrId = 10L,
                            Nazev = "Horror"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HraZanr", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Hra", null)
                        .WithMany()
                        .HasForeignKey("HryHraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnihovnaHer.Data.Models.Zanr", null)
                        .WithMany()
                        .HasForeignKey("ZanryZanrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Hra", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Vydavatel", "Vydavatel")
                        .WithMany("Hry")
                        .HasForeignKey("VydavatelId");

                    b.Navigation("Vydavatel");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.StatusHry", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Hra", "Hra")
                        .WithMany("StatusHer")
                        .HasForeignKey("HraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", "Uzivatel")
                        .WithMany("StatusHer")
                        .HasForeignKey("UzivatelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hra");

                    b.Navigation("Uzivatel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Hra", b =>
                {
                    b.Navigation("StatusHer");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Uzivatel", b =>
                {
                    b.Navigation("StatusHer");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Vydavatel", b =>
                {
                    b.Navigation("Hry");
                });
#pragma warning restore 612, 618
        }
    }
}
