// <auto-generated />
using System;
using KnihovnaHer.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnihovnaHer.Data.Migrations
{
    [DbContext(typeof(KnihovnaHerDbContext))]
    partial class KnihovnaHerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HraZanr", b =>
                {
                    b.Property<long>("HryHraId")
                        .HasColumnType("bigint");

                    b.Property<long>("ZanryZanrId")
                        .HasColumnType("bigint");

                    b.HasKey("HryHraId", "ZanryZanrId");

                    b.HasIndex("ZanryZanrId");

                    b.ToTable("HraZanr");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Hra", b =>
                {
                    b.Property<long>("HraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HraId"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokVydani")
                        .HasColumnType("int");

                    b.Property<long?>("VydavatelId")
                        .HasColumnType("bigint");

                    b.HasKey("HraId");

                    b.HasIndex("VydavatelId");

                    b.ToTable("Hry");

                    b.HasData(
                        new
                        {
                            HraId = 1L,
                            Nazev = "The Witcher 3",
                            RokVydani = 2015,
                            VydavatelId = 2L
                        },
                        new
                        {
                            HraId = 2L,
                            Nazev = "Fortnite",
                            RokVydani = 2017,
                            VydavatelId = 1L
                        },
                        new
                        {
                            HraId = 3L,
                            Nazev = "Battlefield V",
                            RokVydani = 2018,
                            VydavatelId = 3L
                        });
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.StatusHry", b =>
                {
                    b.Property<long>("StatusHryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatusHryId"));

                    b.Property<DateTime?>("DatumDokonceni")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZacatku")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Hodnoceni")
                        .HasColumnType("int");

                    b.Property<long>("HraId")
                        .HasColumnType("bigint");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<string>("UzivatelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StatusHryId");

                    b.HasIndex("HraId");

                    b.HasIndex("UzivatelId");

                    b.ToTable("StatusHer");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Uzivatel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Vydavatel", b =>
                {
                    b.Property<long>("VydavatelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VydavatelId"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VydavatelId");

                    b.ToTable("Vydavatele");

                    b.HasData(
                        new
                        {
                            VydavatelId = 1L,
                            Nazev = "Epic Games"
                        },
                        new
                        {
                            VydavatelId = 2L,
                            Nazev = "Bethesda"
                        },
                        new
                        {
                            VydavatelId = 3L,
                            Nazev = "Electronic Arts"
                        });
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Zanr", b =>
                {
                    b.Property<long>("ZanrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ZanrId"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ZanrId");

                    b.HasIndex("Nazev");

                    b.ToTable("Zanry");

                    b.HasData(
                        new
                        {
                            ZanrId = 1L,
                            Nazev = "Action"
                        },
                        new
                        {
                            ZanrId = 2L,
                            Nazev = "Adventure"
                        },
                        new
                        {
                            ZanrId = 3L,
                            Nazev = "RPG"
                        },
                        new
                        {
                            ZanrId = 4L,
                            Nazev = "Sci-Fi"
                        },
                        new
                        {
                            ZanrId = 5L,
                            Nazev = "Strategy"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HraZanr", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Hra", null)
                        .WithMany()
                        .HasForeignKey("HryHraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnihovnaHer.Data.Models.Zanr", null)
                        .WithMany()
                        .HasForeignKey("ZanryZanrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Hra", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Vydavatel", "Vydavatel")
                        .WithMany("Hry")
                        .HasForeignKey("VydavatelId");

                    b.Navigation("Vydavatel");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.StatusHry", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Hra", "Hra")
                        .WithMany("StatusHer")
                        .HasForeignKey("HraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", "Uzivatel")
                        .WithMany("StatusHer")
                        .HasForeignKey("UzivatelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hra");

                    b.Navigation("Uzivatel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KnihovnaHer.Data.Models.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Hra", b =>
                {
                    b.Navigation("StatusHer");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Uzivatel", b =>
                {
                    b.Navigation("StatusHer");
                });

            modelBuilder.Entity("KnihovnaHer.Data.Models.Vydavatel", b =>
                {
                    b.Navigation("Hry");
                });
#pragma warning restore 612, 618
        }
    }
}
